SELECT YEAR(TRIP_START_DATE) AS year,
	T.TRIP_ID AS tripID,
	FE.FISHING_EVENT_ID AS hookID,
	FE_PARENT_EVENT_ID AS skateID,
	FE_MAJOR_LEVEL_ID AS "set",
	FE_SUB_LEVEL_ID AS skate,
	FE_MINOR_LEVEL_ID AS hook, 
	HOOK_YIELD_CODE AS hookYieldCode
FROM FISHING_EVENT FE
	INNER JOIN TRIP T ON FE.TRIP_ID = T.TRIP_ID 
	INNER JOIN TRIP_SURVEY TS ON TS.TRIP_ID = T.TRIP_ID
	INNER JOIN SURVEY S ON S.SURVEY_ID = TS.SURVEY_ID
	INNER JOIN HOOK_SPECS HS ON HS.FISHING_EVENT_ID = FE.FISHING_EVENT_ID
WHERE SURVEY_SERIES_ID = '14' 
	AND FE_PARENT_EVENT_ID IS NOT NULL 
	AND HOOK_YIELD_CODE IN (2, 6)
GROUP BY T.TRIP_START_DATE, 
	T.TRIP_ID, 
	FE.FISHING_EVENT_ID, 
	FE_PARENT_EVENT_ID,
	FE_MAJOR_LEVEL_ID,
	FE_SUB_LEVEL_ID,
	FE_MINOR_LEVEL_ID, 
	HOOK_YIELD_CODE
ORDER BY hookYieldCode, 
	year, 
	T.TRIP_ID, 
	FE.FISHING_EVENT_ID
	
